services:
  web:
    build: ./src
    image: excel-MP-report:dev
    command: uv run uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    volumes:
      - ./src/:/usr/src/app/
    env_file:
      - .env
    ports:
      - 8000:8000
